import type { Position } from '../types/player';
import type { PlayerAttributes } from '../types/player';

export type AttributeKey = keyof PlayerAttributes;

export const ATTRIBUTE_KEYS: AttributeKey[] = [
  'finishing',
  'speed',
  'dribbling',
  'passing',
  'heading',
  'marking',
  'tackling',
  'positioning',
  'reflexes',
  'aggression',
];

/**
 * Peso (0-1) de cada atributo por posição: quanto maior, mais central o
 * atributo é para a função. Usado tanto para enviesar a geração de valores
 * quanto para calcular a força geral (strength) como média ponderada.
 * Único lugar de balanceamento — ajustar aqui, não espalhado pelo código.
 */
export const POSITION_ATTRIBUTE_WEIGHTS: Record<Position, PlayerAttributes> = {
  GOL: {
    finishing: 0.1,
    speed: 0.2,
    dribbling: 0.1,
    passing: 0.4,
    heading: 0.1,
    marking: 0.2,
    tackling: 0.1,
    positioning: 0.9,
    reflexes: 1.0,
    aggression: 0.1,
  },
  ZAG: {
    finishing: 0.1,
    speed: 0.4,
    dribbling: 0.2,
    passing: 0.4,
    heading: 0.9,
    marking: 1.0,
    tackling: 0.9,
    positioning: 0.7,
    reflexes: 0.1,
    aggression: 0.8,
  },
  LD: {
    finishing: 0.2,
    speed: 0.8,
    dribbling: 0.5,
    passing: 0.6,
    heading: 0.3,
    marking: 0.6,
    tackling: 0.7,
    positioning: 0.5,
    reflexes: 0.1,
    aggression: 0.6,
  },
  LE: {
    finishing: 0.2,
    speed: 0.8,
    dribbling: 0.5,
    passing: 0.6,
    heading: 0.3,
    marking: 0.6,
    tackling: 0.7,
    positioning: 0.5,
    reflexes: 0.1,
    aggression: 0.6,
  },
  ALD: {
    finishing: 0.3,
    speed: 0.9,
    dribbling: 0.6,
    passing: 0.6,
    heading: 0.2,
    marking: 0.4,
    tackling: 0.5,
    positioning: 0.5,
    reflexes: 0.1,
    aggression: 0.5,
  },
  ALE: {
    finishing: 0.3,
    speed: 0.9,
    dribbling: 0.6,
    passing: 0.6,
    heading: 0.2,
    marking: 0.4,
    tackling: 0.5,
    positioning: 0.5,
    reflexes: 0.1,
    aggression: 0.5,
  },
  VOL: {
    finishing: 0.1,
    speed: 0.4,
    dribbling: 0.3,
    passing: 0.7,
    heading: 0.3,
    marking: 0.8,
    tackling: 0.9,
    positioning: 0.9,
    reflexes: 0.1,
    aggression: 0.9,
  },
  MC: {
    finishing: 0.2,
    speed: 0.5,
    dribbling: 0.6,
    passing: 0.9,
    heading: 0.2,
    marking: 0.4,
    tackling: 0.6,
    positioning: 0.8,
    reflexes: 0.1,
    aggression: 0.5,
  },
  MD: {
    finishing: 0.3,
    speed: 0.8,
    dribbling: 0.8,
    passing: 0.6,
    heading: 0.1,
    marking: 0.3,
    tackling: 0.4,
    positioning: 0.5,
    reflexes: 0.1,
    aggression: 0.4,
  },
  ME: {
    finishing: 0.3,
    speed: 0.8,
    dribbling: 0.8,
    passing: 0.6,
    heading: 0.1,
    marking: 0.3,
    tackling: 0.4,
    positioning: 0.5,
    reflexes: 0.1,
    aggression: 0.4,
  },
  MEA: {
    finishing: 0.6,
    speed: 0.6,
    dribbling: 0.9,
    passing: 0.9,
    heading: 0.2,
    marking: 0.1,
    tackling: 0.2,
    positioning: 0.7,
    reflexes: 0.1,
    aggression: 0.3,
  },
  PD: {
    finishing: 0.6,
    speed: 1.0,
    dribbling: 0.9,
    passing: 0.5,
    heading: 0.2,
    marking: 0.1,
    tackling: 0.2,
    positioning: 0.5,
    reflexes: 0.1,
    aggression: 0.3,
  },
  PE: {
    finishing: 0.6,
    speed: 1.0,
    dribbling: 0.9,
    passing: 0.5,
    heading: 0.2,
    marking: 0.1,
    tackling: 0.2,
    positioning: 0.5,
    reflexes: 0.1,
    aggression: 0.3,
  },
  SA: {
    finishing: 0.9,
    speed: 0.7,
    dribbling: 0.7,
    passing: 0.5,
    heading: 0.4,
    marking: 0.1,
    tackling: 0.1,
    positioning: 0.7,
    reflexes: 0.1,
    aggression: 0.4,
  },
  CA: {
    finishing: 1.0,
    speed: 0.6,
    dribbling: 0.5,
    passing: 0.3,
    heading: 0.8,
    marking: 0.1,
    tackling: 0.1,
    positioning: 0.9,
    reflexes: 0.1,
    aggression: 0.5,
  },
};
